<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OpenApiGenerateDocumentsOnBuild>true</OpenApiGenerateDocumentsOnBuild>
    <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)/../../artifacts/openapi</OpenApiDocumentsDirectory>
    <OpenApiGenerateDocumentsOptions>--document-name app --file-name app</OpenApiGenerateDocumentsOptions>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Chronicle.Core/Chronicle.Core.csproj" />
    <ProjectReference Include="../Chronicle.Infrastructure/Chronicle.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
  </ItemGroup>
</Project>
